/*
 * PreferencesJPanel.java
 *
 * Created on 13 January 2007, 06:03
 */

package org.wiztools.jenkryptor;

import javax.swing.SwingUtilities;

/**
 *
 * @author  subhash
 */
public class PreferencesJPanel extends javax.swing.JPanel {
    
    /** Creates new form PreferencesJPanel */
    public PreferencesJPanel() {
        initComponents();
    }
    
    public void setPreferences(final boolean overwriteDest, final boolean delSrc){
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                jcbOverwriteDest.setSelected(overwriteDest);
                jcbDeleteSource.setSelected(delSrc);
            }
        });
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jcbOverwriteDest = new javax.swing.JCheckBox();
        jcbDeleteSource = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jbOk = new javax.swing.JButton();
        jbCancel = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Preferences"));
        jcbOverwriteDest.setText("Overwrite Destination File?");
        jcbOverwriteDest.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jcbOverwriteDest.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jcbDeleteSource.setSelected(true);
        jcbDeleteSource.setText("Delete Source File After Encrypting/Decrypting");
        jcbDeleteSource.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jcbDeleteSource.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jButton1.setText("Restore Default");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbOk.setText("Ok");
        jbOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOkActionPerformed(evt);
            }
        });

        jbCancel.setText("Cancel");
        jbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jButton1)
                        .addGap(23, 23, 23)
                        .addComponent(jbCancel)
                        .addGap(23, 23, 23)
                        .addComponent(jbOk))
                    .addComponent(jcbOverwriteDest, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbDeleteSource, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcbOverwriteDest)
                .addGap(16, 16, 16)
                .addComponent(jcbDeleteSource)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbOk)
                    .addComponent(jButton1)
                    .addComponent(jbCancel))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOkActionPerformed
        Preferences.overwriteDestination_pref = jcbOverwriteDest.isSelected();
        Preferences.deleteSource_pref = jcbDeleteSource.isSelected();
        Globals.MAIN_FRAME.setJDVisible(false);
    }//GEN-LAST:event_jbOkActionPerformed

    private void jbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelActionPerformed
        Globals.MAIN_FRAME.setJDVisible(false);
    }//GEN-LAST:event_jbCancelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SwingUtilities.invokeLater(new Runnable(){
            public void run(){
                jcbOverwriteDest.setSelected(false);
                jcbDeleteSource.setSelected(true);
                Globals.MAIN_FRAME.setJDVisible(false);
            }
        });
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbCancel;
    private javax.swing.JButton jbOk;
    private javax.swing.JCheckBox jcbDeleteSource;
    private javax.swing.JCheckBox jcbOverwriteDest;
    // End of variables declaration//GEN-END:variables
    
}
