#!/bin/sh

#############################################
## http://wiztools.org/project/jEnkryptor/ ##
#############################################

VERSION=1.0b3

## Program logic starts, not to modify! ##

if which java > /dev/null 2>&1
then
    java -jar /usr/share/java/jenkryptor-${VERSION}-jar-with-dependencies.jar $*
else
    echo Java not in PATH
    exit 1
fi

